import '../styles/normalize.css'
import '../styles/generalsans.css'
import '../styles/styles.css'
import '../styles/components/header.css'
import '../styles/components/hero.css'
import '../styles/components/footer.css'
import '../styles/utils.css'